export class AppointmentViewModel {
    PatientId!: number;               // Required, set when booking
    DoctorId?: number;                 // Set before submission
    SpecializationId?: number;         // Set on specialization selection
    DateAndTime!: Date;                // Use Date type to format correctly
    TokenNumber?: string;              // Generated by backend
    ConsultationStatus: boolean = true; // Boolean type for status
    TotalAmount: string = '200';       // Set default value as a string
}
